version: '2'
services:
  webserver:
    build: .
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_enable=1 remote_port=9000
      PHP_IDE_CONFIG: serverName=docker
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: testuser
      DB_PASS: testpassword
      DB_NAME: someDB
  db:
    image: mysql:5.6
    restart: always
    volumes:
      - ./resources:/docker-entrypoint-initdb.d
    environment:
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
      MYSQL_DATABASE: someDB
      MYSQL_ROOT_PASSWORD: someRootPass
